//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlFramework.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SqlFramework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Database&gt;
        ///  &lt;StoredProcedures Namespace=&quot;Database.Tests.StoredProcedures&quot;&gt;
        ///	&lt;Procedure SchemaName=&quot;Core&quot; Name=&quot;GetAllLargeTableItems&quot; /&gt;
        ///	&lt;Procedure SchemaName=&quot;Core&quot; Name=&quot;GetAllLargeTableItemsById&quot; /&gt;
        ///	&lt;Procedure SchemaName=&quot;Core&quot; Name=&quot;GetAllLargeTableItemsByIds&quot; /&gt;
        ///	&lt;Procedure SchemaName=&quot;Core&quot; Name=&quot;SaveSmallTableRows&quot; /&gt;
        ///  &lt;/StoredProcedures&gt;
        ///  &lt;UserDefinedTableTypes Namespace=&quot;Database.Tests.UserDefinedTableTypes&quot;&gt;
        ///	&lt;Type SchemaName=&quot;Core&quot; Name=&quot;LargeT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use [master];
        ///
        ///if db_id(&apos;SqlFramework&apos;) is not null
        ///begin
        ///	alter database [SqlFramework] set single_user with rollback immediate;
        ///	drop database [SqlFramework];
        ///end
        ///go
        ///
        ///create database [SqlFramework];
        ///alter database  [SqlFramework] set recovery simple;
        ///alter database  [SqlFramework] set compatibility_level = 100;
        ///go
        ///
        ///use [SqlFramework];
        ///go
        ///
        ///create schema Core;
        ///go
        ///
        ///create type Core.Name from nvarchar(100);
        ///go
        ///
        ///create type Core.Age from tinyint not null;
        ///go
        ///
        ///create type Core.LargeTab [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateDatabase {
            get {
                return ResourceManager.GetString("CreateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use [master];
        ///
        ///if db_id(&apos;SqlFramework&apos;) is not null
        ///begin
        ///	alter database [SqlFramework] set single_user with rollback immediate;
        ///	drop database [SqlFramework];
        ///end.
        /// </summary>
        internal static string DeleteDatabase {
            get {
                return ResourceManager.GetString("DeleteDatabase", resourceCulture);
            }
        }
    }
}
